# Generated by Django 4.0.5 on 2025-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_status_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
